### ISSUE TITLE
Never worked for me

### ISSUE THREAD

**Issue by jomo** [23x/poetti-soundsystem#1]
Is this hosted somewhere?

IIRC it used to be hosted somewhere but it's now gone.

If you create a new branch called `gh-pages` it should become available at https://23x.github.io/poetti-soundsystem at no cost :sunglasses:

**Comment by lawl** [comment]
server crashed. was too lazy to put it up again. back at the old place.

http://soundsystem.dumbinter.net/#justaskme

**Comment by jomo** [comment]
:+1: thanks
